name: twas_sim
channels:
    - conda-forge
dependencies:
    - python
    - glimix-core
    - numpy-sugar
    - numpy >= 1.14.5
    - pandas >= 0.23.3
    - pandas-plink
    - scipy >= 1.2.0
    - scikit-learn
